install:
  - sudo apt-get update
  - sudo apt-get install libqt5-dev qt5-qmake
  - wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz
  - tar xzvf openssl-1.1.0e.tar.gz
  - cd openssl-1.1.0e
  - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  - make
  - sudo make install

script:
  - qmake -project
  - qmake OneTimeEncryptor.pro
  - make
