install:
  - sudo add-apt-repository ppa:beineri/opt-qt562
  - sudo apt-get update
  - sudo apt-get install qt-latest
  - wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz
  - tar xzvf openssl-1.1.0f.tar.gz
  - cd openssl-1.1.0f
  - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  - make
  - sudo make install

script:
  - qmake -project
  - qmake OneTimeEncryptor.pro
  - make
