dist: trusty
sudo: required

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update>/dev/null
  - sudo apt-get install qt5-default gcc-4.9 g++-4.9>/dev/null
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz
  - tar xzf openssl-1.1.0f.tar.gz
  - cd openssl-1.1.0f
  - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  - make>/dev/null
  - sudo make install>/dev/null 2>&1
  - cd ..
  - qmake -v
  - g++ -v



script:
  - qmake
  - make
