dist: trusty
sudo: required

install:
  - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
<<<<<<< HEAD
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
=======
>>>>>>> aa32321eed285b40b11a8c87cbae2e9d2e37fa44
  - sudo apt-get update
  - sudo apt-get install qt-latest g++-4.9
  - wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz
  - tar xzf openssl-1.1.0f.tar.gz
  - cd openssl-1.1.0f
  - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  - make>/dev/null
  - sudo make install>/dev/null 2>&1
  - cd ..



script:
  - qmake -project
  - qmake OneTimeEncryptor.pro
  - make
