language: cpp
dist: trusty
sudo: required

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - qt5-default
  
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - wget https://github.com/randombit/botan/archive/2.1.0.tar.gz
  - tar xzf 2.1.0.tar.gz
  - cd botan-2.1.0
  - ./configure.py
  - make>/dev/null
  - sudo make install>/dev/null 2>&1
  - cd ..
  - qmake -v
  - g++ -v


  
script:
  - qmake
  - make
